### ISSUE TITLE
Documentation conflicts with reality

### ISSUE THREAD

**Issue by danielquinn** [CurrencyCloud/currencycloud-python#9]
The [documentation for conversion creation](https://developer.currencycloud.com/documentation/api-docs/conversions/post-conversions-create/) states that `term_agreement` is a boolean value and must be `true` for things to go ahead.  However, if you actually send boolean `True` through `currencycloud.Conversion.create`, it barfs complaining that the term_agreement must be true.

The only way to get it to actually work is to pass the literal string `"true"`, which is of course boolean true, but then again so is `"false"`.

If as the documentation states, the server requires a boolean `true`, then the client library needs to accept boolean values.  If however the server requires string `"true"` then the documentation should be amended or the server should be fixed to actually accept boolean values.

**Comment by danielquinn** [comment]
The [documentation for retrieve multiple rates](https://developer.currencycloud.com/documentation/api-docs/rates/get-rates-find/) includes an example request that is not in fact a request for any rate at all, and the example response includes rates for two distinct currency pairs even though the arguments section only allows for one `currency_pair` argument.

When actually querying the API, I'm left **trying to guess** the behaviour:

One rate:

```
curl -X GET --header "X-Auth-Token: [redacted]" https://devapi.currencycloud.com/v2/rates/find?currency_pair=GBPUSD
{"rates":{"GBPUSD":["1.407700","1.408300"]},"unavailable":[]}
```

But how do you get more than one rate?

Passing `currency_pair` multiple times appears to just have the last argument overwrite the rest:

```
curl -X GET --header "X-Auth-Token: [redacted]" 'https://devapi.currencycloud.com/v2/rates/find?currency_pair=GBPUSD&currency_pair=EURCAD'
{"rates":{"EURCAD":["1.495000","1.495500"]},"unavailable":[]}
```

And even using PHP's kooky `[]` format fails, at least this time with a useful error:

```
curl -X GET --header "X-Auth-Token: [redacted]" 'https://devapi.currencycloud.com/v2/rates/find?currency_pair%5B=GBPUSD&currency_pair%5D=EURCAD'
{"error_code":"invalid_extra_parameters","error_messages":{"base":[{"code":"invalid_extra_parameters","message":"Invalid extra parameters:'{:\"currency_pair[\"=>\"GBPUSD\"}'","params":{"parameters":{"currency_pair[":"GBPUSD"}}}]}}
```

So either the documentation is lying and you can't get multiple rates, or you can, and the documentation is simply not documenting it.

**Comment by EAddario** [comment]
The documentation describes parameters and their types from the server's REST invocation perspective and not from any given SDK (as type definition will vary from language to language). It's therefore correct to identify as boolean since it is a defined value in JSON (please see [json.org](https://json.org/))

There is an issue however in that the SDK does not map correctly the Python boolean **True** to the JSON **true**. We may address this in a future release.

Regarding multiple rates retrieval, the documentation wasn't lying but it wasn't being clear either. The correct way to retrieve multiple pairs is to provide the values in a comma separated sequence:
```sh
curl -k -X GET 'https://devapi.currencycloud.com/v2/rates/find?currency_pair=EURGBP,GBPUSD' -H 'X-Auth-Token: deadbeefdeadbeefdeadbeefdeadbeef'
```
or, in the case of the Python SDK:
```python
rate = client.rates.find(currency_pair='EURGBP,GBPUSD')
```
We have addressed this deficiency in our documentation and now offer live testing on selected resources. Please try [Get Detailed Rates](https://www.currencycloud.com/developers/docs/item/get-basic-rates/), enter **EURGBP,GBPUSD** in the **currency_pair** value box and then _Run the Code_

Lastly, it shouldn't have taken this long to answer these questions. But it did, and for that we apologise. We will do much better from now on.
